@echo off
mkdir "Weekend Plans"
mkdir "Hobbies"
mkdir "Favorite Foods"
mkdir "Travel Experiences"
mkdir "Sports"
mkdir "Movies"
mkdir "Music"
mkdir "Books"
mkdir "Weather"
mkdir "Family"
mkdir "Friends"
mkdir "School"
mkdir "Work"
mkdir "Health"
mkdir "Fitness"
mkdir "Technology"
mkdir "Social Media"
mkdir "Pets"
mkdir "Nature"
mkdir "Environment"
mkdir "Politics"
mkdir "News"
mkdir "History"
mkdir "Science"
mkdir "Art"
mkdir "Painting"
mkdir "Cooking"
mkdir "Baking"
mkdir "Gardening"
mkdir "Shopping"
mkdir "Fashion"
mkdir "Cars"
mkdir "Bikes"
mkdir "Public Transport"
mkdir "Holidays"
mkdir "Festivals"
mkdir "Birthdays"
mkdir "Parties"
mkdir "Concerts"
mkdir "Theater"
mkdir "Dance"
mkdir "Photography"
mkdir "Writing"
mkdir "Poetry"
mkdir "Languages"
mkdir "Learning"
mkdir "Education"
mkdir "Teachers"
mkdir "Students"
mkdir "Exams"
mkdir "Jobs"
mkdir "Career"
mkdir "Money"
mkdir "Savings"
mkdir "Investments"
mkdir "Shopping Online"
mkdir "Restaurants"
mkdir "Cafes"
mkdir "Coffee"
mkdir "Tea"
mkdir "Drinks"
mkdir "Alcohol"
mkdir "Smoking"
mkdir "Sleep"
mkdir "Dreams"
mkdir "Relationships"
mkdir "Dating"
mkdir "Marriage"
mkdir "Children"
mkdir "Parenting"
mkdir "Grandparents"
mkdir "Siblings"
mkdir "Cousins"
mkdir "Neighbors"
mkdir "Community"
mkdir "Religion"
mkdir "Spirituality"
mkdir "Meditation"
mkdir "Yoga"
mkdir "Exercise"
mkdir "Running"
mkdir "Swimming"
mkdir "Cycling"
mkdir "Hiking"
mkdir "Camping"
mkdir "Fishing"
mkdir "Hunting"
mkdir "Games"
mkdir "Board Games"
mkdir "Video Games"
mkdir "Chess"
mkdir "Cards"
mkdir "Puzzles"
mkdir "Riddles"
mkdir "Jokes"
mkdir "Comedy"
mkdir "TV Shows"
mkdir "Series"
mkdir "Documentaries"
mkdir "Reality TV"
echo Folders created successfully.